### ISSUE TITLE
Uncaught (in promise) TypeError

### ISSUE THREAD

**Issue by viveknath3222** [codrops/ScrollBasedLayoutAnimations#2]
Hi,

If I try to add only one section and deleting all other animated sections, am getting below error

index.js:49 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at triggerFlipOnScroll (index.js:49:35)
    at index.js:112:9
    at Array.forEach (<anonymous>)
    at scroll (index.js:110:15)
    at index.js:119:2
    
    What might be the issue?

**Comment by kyndaqtepammy** [comment]
did you find a solution?
